### ISSUE TITLE
Database File Missing

### ISSUE THREAD

**Issue by amritcoder** [Connorbub/friendNet#1]
Hello my friend, I like this script but seems database file is missing. 
Please upload database file. 
Thanks

**Comment by Connorbub** [comment]
Sorry about the delay, I just uploaded an SQL file to the main folder of the repository, and I also attached it to this response
[socialnetwork.sql.zip](https://github.com/Connorbub/friendNet/files/6248303/socialnetwork.sql.zip)
. It should work if you simply import it into a database. If you have any issues, let me know.
